/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_HelloWorld */

#ifndef _Included_org_example_HelloWorld
#define _Included_org_example_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_HelloWorld
 * Method:    printHelloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_example_HelloWorld_printHelloWorld
  (JNIEnv *, jobject);

/*
 * Class:     org_example_HelloWorld
 * Method:    say
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_example_HelloWorld_say
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
